// src/data.js
export const restaurant = {
  name: "Punjab Grill",
  address: "3Rd Floor, Infiniti Mall, Unit No. Tf 326, 2, Ne...",
  popularItems: 5,
  UPI_ID: '8380888360@pthdfc',
  image: "https://example.com/restaurant-image.jpg",
  deliveryCharges : 50,
  expectedDeliveryTime: 50
};

export const menuItems = [
  {id: "00", menu: "Coldrinks", submenu: "Vanilla", half_price: 0, full_price: 40, available: 1, description:'4 chapatya varan bhat 2 bhajya',},
  {id: "001", menu: "Coldrinks", submenu: "(Big) Butter Scotch Kon", half_price: 2, full_price: 4, available: 1, description:'4 chapatya varan bhat 2 bhajya'},
  {id: "002", menu: "Coldrinks", submenu: "American Nuts", half_price: 0, full_price: 2, available: 1, description:''},
  {id: "003", menu: "Coldrinks", submenu: "Butter Scotch", half_price: 0, full_price: 1, available: 1, description:''},
  { id: "01", menu: "Coldrinks", submenu: "Vanilla", half_price: 0, full_price: 40, available: 1, description:'' },
  { id: "011", menu: "Coldrinks", submenu: "(Big) Butter Scotch Kon", half_price: 2, full_price: 4, available: 1, description:'4 chapatya varan bhat 2 bhajya' },
  { id: "017", menu: "Coldrinks", submenu: "American Nuts", half_price: 0, full_price: 2, available: 1, description:'4 chapatya varan bhat 2 bhajya' },
  { id: "02", menu: "Coldrinks", submenu: "Butter Scotch", half_price: 0, full_price: 1, available: 1, description:'' },
  { id: "021", menu: "Coldrinks", submenu: "afgan dry fruit", half_price: 0, full_price: 25, available: 1, description:'4 chapatya varan bhat 2 bhajya' },
  { id: "022", menu: "Coldrinks", submenu: "cone", half_price: 0, full_price: 35, available: 1, description:'' },
  { id: "03", menu: "Coldrinks", submenu: "KAJU DRAKSH", half_price: 0, full_price: 30, available: 1, description:'4 chapatya varan bhat 2 bhajya' },
  { id: "04", menu: "Coldrinks", submenu: "Kesar Pista", half_price: 0, full_price: 2, available: 1, description:'4 chapatya varan bhat 2 bhajya' },
  { id: "1", menu: "Khet Ki Hariyali", submenu: "Lasuni Methi", half_price: 0, full_price: 170, available: 1, description:'4 chapatya varan bhat 2 bhajya' },
  { id: "10", menu: "Khana Khajana", submenu: "Palak Paneer", half_price: 0, full_price: 180, available: 1, description:'' },
  { id: "102", menu: "EXTRA", submenu: "EXTRA CASH", half_price: 0, full_price: 1, available: 0 },
  { id: "104", menu: "Khana Khajana", submenu: "Paneer Jal Frazy", half_price: 0, full_price: 300, available: 1, description:'4 chapatya varan bhat 2 bhajya' },
  { id: "106", menu: "Soup", submenu: "Tomato Soup", half_price: 0, full_price: 90, available: 1, description:'4 chapatya varan bhat 2 bhajya' },
  { id: "107", menu: "Khana Khajana", submenu: "Paneer Panjabi", half_price: 0, full_price: 290, available: 1, description:'4 chapatya varan bhat 2 bhajya' },
  { id: "108", menu: "Khana Khajana", submenu: "Paneer Chatpata", half_price: 0, full_price: 290, available: 1, description:'4 chapatya varan bhat 2 bhajya' },
  { id: "109", menu: "Khane Ke Sath", submenu: "Tandoori Roti", half_price: 0, full_price: 17, available: 1, description:'4 chapatya varan bhat 2 bhajya' },
  { id: "11", menu: "Khana Khajana", submenu: "Shahi Paneer", half_price: 0, full_price: 180, available: 1, description:'' },
  { id: "111", menu: "Khane Ke Sath", submenu: "Bajra Bhakar", half_price: 0, full_price: 22, available: 1, description:'' },
  { id: "113", menu: "Khane Ke Sath", submenu: "Sadha Paratha", half_price: 0, full_price: 45, available: 1, description:'4 chapatya varan bhat 2 bhajya' },
  { id: "114", menu: "Khane Ke Sath", submenu: "Aloo Paratha", half_price: 0, full_price: 75, available: 1, description:'4 chapatya varan bhat 2 bhajya' },
  { id: "116", menu: "Khane Ke Sath", submenu: "Butter Bajra Bhakar", half_price: 0, full_price: 30, available: 1, description:'4 chapatya varan bhat 2 bhajya' },
  { id: "117", menu: "Khane Ke Sath", submenu: "Butter Roti", half_price: 0, full_price: 22, available: 1, description:'' },
  { id: "118", menu: "Khane Ke Sath", submenu: "Butter Tawa Chapati", half_price: 0, full_price: 22, available: 1, description:'' },
  { id: "119", menu: "Khane Ke Sath", submenu: "Tawa Chapati", half_price: 0, full_price: 17, available: 1, description:'' },
  { id: "12", menu: "Khana Khajana", submenu: "Paneer Bhurji", half_price: 0, full_price: 200, available: 1, description:'' },
  { id: "120", menu: "Khane Ke Sath", submenu: "Butter Naan", half_price: 0, full_price: 55, available: 1, description:'4 chapatya varan bhat 2 bhajya' },
  { id: "121", menu: "Pappad & Salad", submenu: "Nagli Roasted", half_price: 0, full_price: 20, available: 1, description:'4 chapatya varan bhat 2 bhajya' },
  { id: "123", menu: "Coldrinks", submenu: "Bailey", half_price: 0, full_price: 20, available: 1, description:'4 chapatya varan bhat 2 bhajya' },
  { id: "124", menu: "Lassi", submenu: "Dahi Plate", half_price: 0, full_price: 60, available: 1, description:'4 chapatya varan bhat 2 bhajya' },
  { id: "125", menu: "Coldrinks", submenu: "MATTHA", half_price: 0, full_price: 30, available: 1, description:'4 chapatya varan bhat 2 bhajya' },
  { id: "126", menu: "Lassi", submenu: "Sweet Lassi", half_price: 0, full_price: 70, available: 1, description:'4 chapatya varan bhat 2 bhajya' },
  { id: "129", menu: "Pappad & Salad", submenu: "Bibdi Papad", half_price: 0, full_price: 80, available: 1, description:'4 chapatya varan bhat 2 bhajya' },
  { id: "13", menu: "Khana Khajana", submenu: "Paneer Butter Masala", half_price: 0, full_price: 180, available: 1, description:'4 chapatya varan bhat 2 bhajya' },
  { id: "132", menu: "Pappad & Salad", submenu: "Bibdi Roasted", half_price: 0, full_price: 30, available: 1, description:'' },
  { id: "133", menu: "Khane Ke Sath", submenu: "Jwari Bhakar", half_price: 0, full_price: 22, available: 1, description:'4 chapatya varan bhat 2 bhajya' },
  { id: "134", menu: "Khandeshi Special", submenu: "Kalna Bhakar", half_price: 0, full_price: 30, available: 1, description:'4 chapatya varan bhat 2 bhajya' },
  { id: "140", menu: "Rice", submenu: "Masala Rice", half_price: 0, full_price: 150, available: 1, description:'' },
  { id: "142", menu: "Khandeshi Special", submenu: "Gud Kala", half_price: 0, full_price: 110, available: 1, description:'4 chapatya varan bhat 2 bhajya' },
  { id: "143", menu: "Starters", submenu: "Harabhara Kabab", half_price: 0, full_price: 190, available: 1, description:'4 chapatya varan bhat 2 bhajya' },
];